mutation GroupUpdate($id: UUID!, $lastchange: DateTime!, $name: String) {
  result: groupUpdate(group: {id: $id, lastchange: $lastchange, name: $name}) {
    id
    msg
    result: group {
      ...Group
    }
  }
}
fragment Group on GroupGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  
  created
  createdby { id email }
  changedby { id email }
  
  email
  valid
  grouptype { id name }
  subgroups { id name }
  mastergroup { id name }
}
