mutation GroupTypeUpdate($id: UUID!, $lastchange: DateTime!, $name: String) {
  result: groupTypeUpdate(groupType: {id: $id, lastchange: $lastchange, name: $name}) {
    id
    msg
    result: groupType {
      ...GroupType
    }
  }
}


fragment GroupType on GroupTypeGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  
  created
  createdby { id email }
  changedby { id email }
}
