query RoleCategoryById($id: UUID!) {
  result: roleCategoryById(id: $id) {
    ...RoleCategory
  }
}


fragment RoleCategory on RoleCategoryGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  
  created
  createdby { id email }
  changedby { id email }
  rbacobject { id }
}