mutation MembershipInsert($id: UUID!, $user_id: UUID!, $group_id: UUID!, $valid: Boolean, $startdate: DateTime, $enddate: DateTime) {
  result: membershipInsert(membership: {id: $id, userId: $user_id, groupId: $group_id, valid: $valid, startdate: $startdate, enddate: $enddate }) {
    id
    msg
    result: membership {
      __typename
      id
      lastchange
    }
  }
}