mutation MembershipUpdate($id: UUID!, $lastchange: DateTime!, $valid: Boolean, $startdate: DateTime, $enddate: DateTime) {
  result: membershipUpdate(
    membership: {id: $id, lastchange: $lastchange, valid: $valid, startdate: $startdate, enddate: $enddate}
  ) {
    id
    msg
    result: membership {
      ...Membership
    }
  }
}

fragment Membership on MembershipGQLModel {
  __typename
  id
  lastchange
  valid
}