mutation RoleTypeUpdate($id: UUID!, $lastchange: DateTime!, $name: String) {
  result: roleTypeUpdate(roleType: {id: $id, lastchange: $lastchange, name: $name}) {
    id
    msg
    result: roleType {
      ...RoleType
    }
  }
}


fragment RoleType on RoleTypeGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  
  created
  createdby { id email }
  changedby { id email }
}
